os: linux
dist: bionic
language: shell

addons:
  apt:
    packages:
      - gnupg wget grep sed

jobs:
  # Test these packages. Don’t include dependencies here, only leaf packages.
  include:
  - env: PACKAGE=python-asyncssh
  - env: PACKAGE=jupyter-zpid
  - env: PACKAGE=python-jupyterlab
  - env: PACKAGE=python-sanic
  - env: PACKAGE=nfs4-acl-tools
  # Allow rstudio-server-zpid to fail, because usually it takes too long.
  allow_failures:
  - env: PACKAGE=rstudio-server-zpid

install: |
  travis_retry wget http://guix.gnu.org/install.sh -O guix-install.sh
  travis_retry wget "https://sv.gnu.org/people/viewgpg.php?user_id=15145" -qO - | gpg --import -
  echo -e 'y\ny' | sudo bash guix-install.sh
  sudo mkdir -p /var/guix/profiles/per-user/travis
  sudo chown travis:travis /var/guix/profiles/per-user/travis
  travis_retry guix pull --fallback --verbosity=0

# Reduced verbosity, so we don’t hit Travis’ build log limits
script: |
  export PATH="~/.config/guix/current/bin${PATH:+:}$PATH"
  guix build --verbosity=1 -L . --no-grafts --fallback $PACKAGE

