name: build
on:
  push:
  pull_request:
  schedule:
    # weekly builds, making sure everything still works with guix-proper
    - cron:  '39 3 * * 0'
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      # building independent packages, don’t abort entire build if one fails
      fail-fast: false
      matrix:
        package:
          - python-asyncssh
          # this builds python-notebook as well
          - python-jupyterlab
          - python-sanic
          - rstudio-server-zpid
    steps:
      - name: Guix cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/guix
          # use a key that (almost) never matches
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build package ${{ matrix.package }}
        run: guix build -L . ${{ matrix.package }}
